### ISSUE TITLE
How stop workflow when the plan detects no changes

### ISSUE THREAD

**Issue by hspecter758** [hashicorp/setup-terraform#100]
What is the easiest way to find if the "terraform plan" command detect zero changes so I can stop the workflow and don't call "terraform apply"?
 
With the previous edition this action (hashicorp/terraform-github-actions) I could use a condition like below:

```
      - name: 'Terraform Apply'
        if: steps.tf_plan.outputs.tf_actions_plan_has_changes == 'true'
        id: terraform_apply
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'apply'
```

How can I do have a similar condition with `hashicorp/setup-terraform` ?

**Comment by johnbooth** [comment]
Is this feature going to be added back into this action in the future? 

I had to create a workaround for this by adding the -detailed-exitcode to the terraform plan and creating my own error conditions and checks to see if I should run the apply job.
One of the downsides of this approach is that I see failures in the annotations when changes are required because the terraform plan exit code is 2.   

```yaml
      - name: Terraform Plan - https://www.terraform.io/docs/commands/plan.html
        id: plan
        run: terraform plan -detailed-exitcode -input=false -out=plan.out
        continue-on-error: true

      - name: Check for Plan Failure
        if: steps.plan.outputs.exitcode == 1
        run: exit 1

    outputs:
      planExitcode: ${{ steps.plan.outputs.exitcode }}

  apply:
    name: "Terraform: apply"
    needs: plan
    if: needs.plan.outputs.planExitcode == 2
    runs-on: ubuntu-latest
```
