### ISSUE TITLE
Version is not respected

### ISSUE THREAD

**Issue by gerryfletch** [hashicorp/setup-terraform#105]
The latest terraform, `v0.15.0` introduced a [bug](https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1165), so I tried to hardcode the version to the newly released `v0.15.1`, which errors `No matching version found`. 

Downgrading the version to `v0.14.9` output the correct version in the `setup-terraform` stage, but the consequent `terraform plan` used the latest:

```
Run hashicorp/setup-terraform@v1
  with:
    cli_config_credentials_token: ***
    terraform_version: 0.14.9
    cli_config_credentials_hostname: app.terraform.io
    terraform_wrapper: true
 ```
 ```
 Waiting for the plan to start...

Terraform v0.15.0
on linux_amd64
Configuring remote state backend...
Initializing Terraform configuration...
╷
│ Error: Error in function call
│ 
│   on .terraform/modules/eks.eks/outputs.tf line 3, in output "cluster_id":
│    3:   value       = element(concat(aws_eks_cluster.this.*.id, list("")), 0)
│ 
│ Call to function "list" failed: the "list" function was deprecated in
│ Terraform v0.12 and is no longer available; use tolist([ ... ]) syntax to
│ write a literal list.
...
```
