### ISSUE TITLE
Terraform init reports failed to query provider packages via Github Actions

### ISSUE THREAD

**Issue by devopsangel** [hashicorp/setup-terraform#117]
Hi Folks, today I started getting this issue and it worked before with no issues. Dunno what is going on  and I could not find anything that could cause this issue:

![image](https://user-images.githubusercontent.com/54945914/121434991-29263780-c94c-11eb-9f40-eaab43d329e2.png)

My provider file looks like this:

```yaml
terraform {
  required_version = ">= 0.15"
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "3.71.0"
    }

    google-beta = {
      source  = "hashicorp/google-beta"
      version = "3.71.0"
    }
  }
}

provider "google" {
  alias = "default"

  user_project_override = true
}
```

My action file config:

```yaml
jobs:
  plan:
    name: 'terraform plan'
    runs-on: ubuntu-latest
    # On pull request to main, plan infrastructure changes according to Terraform configuration files
    if: github.event_name == 'pull_request'

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.5
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # Write the gcp credentials to a temp file
      - name: Setup Creds
        run: |-
            echo ${GCP_CREDS} > gcp_key.json
            cat gcp_key.json
        env: 
            GCP_CREDS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_DEFAULT }}

      - name: Terraform Init
        run: terraform init

      # Checks that all Terraform configuration files adhere to a canonical format
      - name: Terraform Format
        run: terraform fmt -check

```
