### ISSUE TITLE
sensitive values exposed

### ISSUE THREAD

**Issue by ZebraFlesh** [hashicorp/setup-terraform#14]
If an output marked as sensitive is specifically output, then the sensitive value is exposed in the workflow log.

For example, if I have the following outputs:
```yaml
output "access_key_id" {
  value       = aws_iam_access_key.user.id
  description = "Access key id for test user"
  sensitive   = true
}

output "secret_access_key" {
  value       = aws_iam_access_key.user.secret
  description = "Secret access key for test user"
  sensitive   = true
}
```
I see the following output from `terraform apply`:
```
Outputs:

access_key_id = <sensitive>
secret_access_key = <sensitive>
```

However, if I try the following:
```
  - id: show-secret
    run: terraform output secret_access_key
  - run: |
      echo "::add-mask::${{ steps.show-secret.outputs.stdout }}"
      echo "${{ steps.show-secret.outputs.stdout }}"
```
I see the following output in the Actions log:
```
echo "::add-mask::<actual value>
  "
echo "<actual value>
  "
```

Consumers of this action are not able to mask the values themselves due to Github Actions' streaming output. According to [this comment](https://github.com/actions/runner/issues/475#issuecomment-635651102), this action would need to call `set-mask` before calling `set-output`.

**Comment by jwenz723** [comment]
I'm not certain of this, but this might obfuscate the value for you:

```
  - id: show-secret
    run: terraform output secret_access_key
  - env:
      SECRET_KEY: ${{ steps.show-secret.outputs.stdout }}
    run: |
      echo "::add-mask::$SECRET_KEY"
      echo "$SECRET_KEY"
```

**Comment by ericsampson** [comment]
@aeschright would you be able to triage this? Seems not great from a security POV. Thanks!

**Comment by riosje** [comment]
I guys this issue is a painful since we can't use standard output without exposing my credentials and API keys.

**Comment by brettcurtis** [comment]
I'm seeing a similar issue and not sure if it's due to this action or the way I'm passing secret vars using GitHub called workflows. 

The chunk of my called workflow:

```yaml
      - name: Terraform Plan - https://www.terraform.io/docs/commands/plan.html
        id: plan
        run: terraform plan -detailed-exitcode -input=false -out=plan.out ${{ inputs.tf_plan_args}} ${{ secrets.tf_plan_secret_args }}
        continue-on-error: true
```

And the caller workflow:

```yaml
jobs:
  global_infra:
    name: "Infra: global"
    uses: lzysh/github-terraform-called-workflows/.github/workflows/gcp-plan-and-apply-called.yml@v1.0.0
    if: ${{ github.actor != 'dependabot[bot]' }}
    with:
      checkout_ref: ${{ github.ref }}
      github_env: "Acceptance Infrastructure: Global"
      terraform_version: 1.0.10
      tf_plan_args: -var-file=tfvars/acc.tfvars
      tf_state_bucket: devops-tools-tf6782e9-prod-tf-state-pre-prod
      tf_workspace: shared-services-global-infra-acc
      working_dir: global
    secrets:
      gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
      service_account_key: ${{ secrets.GCP_DEVOPS_PRE_PROD_GITHUB_SA_KEY }}
      ssh_key: ${{ secrets.RO_SSH_PRIV_KEY }}
      tf_plan_secret_args: >-
        -var="bridgecrew_token=${{ secrets.BRIDGECREW_TOKEN }}"
        -var="datadog_api_key=${{ secrets.DATADOG_API_KEY }}"
        -var="datadog_app_key=${{ secrets.DATADOG_APP_KEY }}"
        -var="billing_id=${{ secrets.BILLING_ID }}"
```

Everything in `tf_plan_secret_args` is printed out in blue text when the plan runs.
