### ISSUE TITLE
Error: This resource can only be used in the context of an organization, "" is a user.

### ISSUE THREAD

**Issue by michaelshire** [hashicorp/setup-terraform#141]
I'm using the basic example to validate tf files on a pull request.  The tf files are to modify GitHub Org (members, repos, teams, etc).  The `terraform plan` works on my local cli (Terraform v1.1.1).

GitHub Action main.yaml
```
# This is a basic workflow to help you get started with Actions

name: Terraform evaluation on pull request

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.1

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      - uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outputs.stdout }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
```

Errors out in the `Terraform Plan` step:

```
Run terraform plan -no-color
  terraform plan -no-color
  shell: /usr/bin/bash -e {0}
  env:
    TERRAFORM_CLI_PATH: /home/runner/work/_temp/a3e34fab-63e1-4923-a3c6-f3bff05666a3
/home/runner/work/_temp/a3e34fab-63e1-4923-a3c6-f3bff05666a3/terraform-bin plan -no-color
github_membership.membership_for_michaelshire: Refreshing state... [id=ShireOrg:michaelshire]
github_repository.repository345: Refreshing state... [id=repository345]
github_repository.repository234: Refreshing state... [id=repository234]

Error: This resource can only be used in the context of an organization, "" is a user.

  with github_membership.membership_for_michaelshire,
  on shireorg_membership.tf line 2, in resource "github_membership" "membership_for_michaelshire":
   2: resource "github_membership" "membership_for_michaelshire" {

Error: Terraform exited with code 1.
Error: Process completed with exit code 1.
```
