### ISSUE TITLE
Logging and Output to Determine Installed Terraform CLI Version

### ISSUE THREAD

**Issue by bflad** [hashicorp/setup-terraform#143]
## Version

v1.3.2 (current v1)

## Description

When using a non-pinned constraint, e.g.

```yaml
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.1.*'
```

This action does not provide any indication of the actually installed Terraform CLI version. This can make debugging more difficult, especially in matrix-based testing.

## Workaround

Manually run `terraform version` as its own command.

```yaml
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ matrix.terraform }}
        terraform_wrapper: false
    - run: terraform version
```

In the Actions UI:

```text
Terraform v1.1.2
on linux_amd64
```

## Proposals

A first proposal would be to have the action automatically run `terraform version` (potentially with the `-json` flag where supported) and informationally log the command's output. This has the added benefit of always showing the version regardless of other workflow configuration and verifying the install upfront.

A second proposal would be to further handle the `terraform version` output by parsing it to extract the actual version, then saving that as an action output (e.g. `terraform_version` or `cli_version`). This would allow downstream steps to either output the version manually or use that version for further logic.

## References

* Related: https://github.com/hashicorp/setup-terraform/issues/130
