### ISSUE TITLE
Request -var and -vars-file

### ISSUE THREAD

**Issue by mimyrtek** [hashicorp/setup-terraform#163]
I would like to request the ability to pass in -var or -vars file to the runs , if possible

**Comment by aimerib** [comment]
This would indeed be useful. For my specific use case, since I only had a handful of vars, I passed them via the env key and I no longer use a vars file. If you have tens or hundreds of vars, this might not work for you, but for me this worked, so leaving it here for others:
```yaml
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
        env:
          TF_VAR_do_token: "${{ env.DO_TOKEN }}"
          TF_VAR_ssh_fingerprint: "${{ env.SSH_FINGERPRINT }}"
```

and inside my `.tf` file:
```terraform
variable "do_token" {}
variable "ssh_fingerprint" {}

provider "digitalocean" {
  token = var.do_token
}

resource "digitalocean_droplet" "do-droplet" {
  image         = "ubuntu-22-10-x64"
  name          = "droplet"
  region        = "nyc3"
  size            = "s-1vcpu-1gb"
  ssh_keys   = [var.ssh_fingerprint]
}
```
