### ISSUE TITLE
terraform init -  `remote` backend with the `prefix` argument

### ISSUE THREAD

**Issue by flamingo09-devops** [hashicorp/setup-terraform#18]
I am using the `remote` backend (terraform cloud) with the `prefix` argument.

Main.tf - 
terraform {
  backend "remote" {
    hostname     = "app.terraform.io"
    organization = "XYZ"
    workspaces {
      prefix = "action-workflow-"
    }
  }
}

**Case-1:**
terraform.yml -
  name: 'Terraform Init'
  run: terraform init

Workflow -  gettting "The operation was canceled" as I am using prefix for workspace and need to select one.  See below - 

Run terraform init
/home/runner/work/_temp/75476658-e44d-420f-8a05-66e146748486/terraform-bin init

Initializing the backend...

Successfully configured the backend "remote"! Terraform will automatically
use this backend unless the backend configuration changes.

The currently selected workspace (default) does not exist.
  This is expected behavior when the selected workspace did not have an
  existing non-empty state. Please enter a number to select a workspace:
  
  1. terraform-azure
  2. tf-az

##[error]The operation was canceled.

**Case-2:**

Trying to pass argument and enviornemnt. 

- name: 'Terraform Init' 
  run: terraform init
  with:
    args: '-backend-config="token=${{ secrets.TF_API_TOKEN }}" -backend-config="organization=XYZ"'
  env:
    TF_WORKSPACE: tf-az   # suffix after  action-workflow-, complete workspace name is action-workflow-tf-az

Workflow - 
![image](https://user-images.githubusercontent.com/59627342/83779265-b8be4980-a659-11ea-8cda-da3fab65683e.png)

**Comment by MightGainer** [comment]
Hi! I had the same issue. This worked for me:
```yaml
- name: "Terraform Init"
  id: init
  run: terraform init
     -backend-config="access_key=${{ secrets.TF_BACKEND_ACCESS_KEY }}"
     -backend-config="secret_key=${{ secrets.TF_BACKEND_SECRET_KEY }}"
```

**Comment by tedmiston** [comment]
This may be new since this issue was created but the currently recommended syntax from https://github.com/hashicorp/setup-terraform#usage works for me:

```yaml
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
```

The only caveat was that I had to set the `TF_WORKSPACE` env var at the job level.

https://support.hashicorp.com/hc/en-us/articles/360043550953-Selecting-a-workspace-when-running-Terraform-in-automation
