### ISSUE TITLE
Read terraform version from a .terraformrc file

### ISSUE THREAD

**Issue by nitrocode** [hashicorp/setup-terraform#208]
Instead of hard coding the version in the workflow, it would be nice to have it read it from a file similar to how [`actions/setup-node@v3`](https://github.com/actions/setup-node) reads from `.nvmrc`

```yaml
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
```

Something like this perhaps ?

```yaml
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version_file: '.terraformrc'
```

**Comment by jasonhuling** [comment]
I second this, but would prefer pulling from `.terraform-version` or from `required_version` in the terraform block.

**Comment by RichiCoder1** [comment]
+1 specifically for `.terraform-version`. Would be willing to PR that too.

**Comment by jgrumboe** [comment]
I also believe `.terraform-version` is better, because `tfenv` also respects it - so two "two birds with one stone" 😁

**Comment by marcofranssen** [comment]
:+1: for the `.terraform-version`.

**Comment by iniinikoski** [comment]
Really good idea, to use .terraform-version. Also thinking, .terraformrc is reserved for this use: https://www.terraform.io/cli/config/config-file

**Comment by karelbemelmans** [comment]
It would be nice to have it in the setup action, but for now you can just do it this way:
````
      - name: Set variables
        run: |
          TF_VERSION=$(cat .terraform-version)
          echo "TF_VERSION=$TF_VERSION" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

````

**Comment by nitrocode** [comment]
@karelbemelmans that's a good workaround.

I would propose a minor tweak to the version retrieval to allow comments in the file

```yaml
      - name: Set variables
        run: |
          TF_VERSION=$(grep -vP '^[\s]?#' .terraform-version)
          echo "TF_VERSION=$TF_VERSION" >> $GITHUB_ENV
```

```sh
✗ cat .terraform-version
# this is a good version
1.2.3
✗ grep -vP '^[\s]?#' .terraform-version
1.2.3
```

**Comment by stevehipwell** [comment]
@karelbemelmans the spec for `.terraform-version` supports using a regex to calculate the correct version which isn't compatible with this action or the library used to download Terraform; these both need Terraform compatible version ranges. To support `.terraform-version` spec regex patterns you'd need an additional step to download the available versions and grep through them (`grep -e` in the docs).

**Comment by jkroepke** [comment]
For users who liked to use the required_version block instead .terraform-version file, we are using and offer a action that use-case.

https://github.com/cloudeteer/actions/tree/main/get-terraform-version

**Comment by nitrocode** [comment]
Very cool! Here is an except from the above.

```yaml
name: Setup Terraform

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Terraform version
        id: terraform_version
        uses: cloudeteer/actions/get-terraform-version@main

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ steps.terraform_version.output.required_version }}
```

**Comment by danielcompton** [comment]
Also, for those who don't want to use an extra action, we do this:

```yaml
      - name: Set Terraform version
        run: |
          TF_VERSION=$(cat .terraform-version)
          echo "TF_VERSION=$TF_VERSION" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: ${{ env.TF_VERSION }}
```

You could also do something similar with Actions outputs if you preferred that.
