### ISSUE TITLE
unable to install google-beta provider

### ISSUE THREAD

**Issue by kevin-shelaga** [hashicorp/setup-terraform#21]
edit: I should add that I can run this provider locally with terraform just fine. 

```
resource "google_container_cluster" "primary" {
  provider                 = google-beta
  project                  = var.project
  name                     = var.cluster_name
  location                 = "northamerica-northeast1-a"
  remove_default_node_pool = "true"
  network                  = var.network
  subnetwork               = var.subnetwork
  min_master_version       = var.min_master_version
  node_version             = var.node_version
  release_channel {
    channel = var.release_channel
  }
```

```
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      id: init
      run: terraform init
```

```
Initializing provider plugins...
- Finding latest version of hashicorp/google-beta...
- Finding latest version of hashicorp/google...
- Finding latest version of -/google...
- Finding latest version of -/google-beta...
- Installing hashicorp/google v3.26.0...
- Installed hashicorp/google v3.26.0 (signed by HashiCorp)
- Installing -/google v3.26.0...
- Installed -/google v3.26.0 (signed by HashiCorp)
- Installing -/google-beta v3.26.0...
- Installed -/google-beta v3.26.0 (signed by HashiCorp)

Error: Failed to install providers

Could not find required providers, but found possible alternatives:

  hashicorp/google-beta -> terraform-providers/google-beta

If these suggestions look correct, upgrade your configuration with the
following command:
    terraform 0.13upgrade .

##[error]Terraform exited with code 1.
##[error]Process completed with exit code 1.
```
