### ISSUE TITLE
terraform import command

### ISSUE THREAD

**Issue by bortek** [hashicorp/setup-terraform#237]
In my manual terraform flow where I build VMs in vsphere I have the followinhg steps

terraform init
terraform import vsphere_folder.folder /Mycluster
terraform plan
terraform apply

Now I am trying to put all this in Github Actions using this code repo. But I cannot find if there is a way to implement "terraform import" step . How do I do it?

**Comment by ngeorger** [comment]
You can do it by adding the backend config first and then create a new step. In my case I use consul for the state, replace the values in your case:

```yaml
name: terraform-staging-v2
on:
  push:
    branches:
      - main
    paths:
        - infra/**
        - .github/workflows/terraform-staging-v2.yaml

  workflow_dispatch:
    inputs:
      destroy:
        description: 'Run terraform destroy?'
        required: true
        type: choice
        default: 'false'
        options:
          - 'true'
          - 'false'
      apply:
        description: 'Run terraform apply?'
        required: true
        type: choice
        default: 'false'
        options:
          - 'true'
          - 'false'
      run_cmd:
        description: 'Run terraform command?'
        required: false
        type: choice
        default: 'false'
        options:
          - 'true'
          - 'false'
      # value_cmd:
      #   description: "Type your custom command"
      #   type: string
      #   required: false
      #   default: ''echo "Hello World'

jobs:
  terraform-staging-plan:
    runs-on: ubuntu-latest
    environment: staging
    permissions:
      contents: write
      id-token: write
    defaults:
      run:
        shell: bash
        working-directory: infra/

    steps:
      - uses: actions/checkout@v3
        name: get the latest code
        with:
          fetch-depth: 3
        id: checkout


      - name: setup tf
        id: setup_terraform
        uses: hashicorp/setup-terraform@v2



      - name: Terraform Init
        id: init
        # continue-on-error: false
        env:
          TF_LOG: DEBUG
        run: |
              terraform init -backend=true \
                -backend-config=path=${{ env.consul_base_path }}/${{ env.environment }}/terraform.tfstate \
                -backend-config=address=${{ env.TF_VAR_address }} \
                -backend-config=access_token=${{ env.CONSUL_HTTP_TOKEN }} \
                -backend-config=datacenter=${{ env.TF_VAR_datacenter }} \
                -backend-config=scheme='https'

      - name: terraform-custom-cmd
        id: custom
        # if: startsWith(github.ref, 'refs/tags/infra')
        env:
          VALUE_CMD: ${{ github.event.inputs.value_cmd }}
          RUN_CMD: ${{ github.event.inputs.run_cmd }}      
        if: env.RUN_CMD == 'true'
        run: |
          echo "Running custom command: ${{ github.event.inputs.value_cmd }}"
          $SHELL ${{ github.event.inputs.value_cmd }} || echo ${{ env.VALUE_CMD }} | $SHELL
        # continue-on-error: true

      
```
