### ISSUE TITLE
Terraform Init working on push but not pull_request

### ISSUE THREAD

**Issue by ryanshepps** [hashicorp/setup-terraform#251]
I'm looking to `terraform plan` in a workflow, but `terraform init` is only working on a workflow triggered by a push, and not a pull_request. 

Workflow file:

```yaml
name: Plan Changes

on: 
  push:
  pull_request:

jobs:
  plan:

    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 'Authenticate with Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          create_credentials_file: true
          workload_identity_provider: 'projects/<project number>/locations/global/workloadIdentityPools/<identity pool>/providers/<identity provider>'
          service_account: 'github-actions@<project id>.iam.gserviceaccount.com'

      - name: 'Setup up Google Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Setup Terraform'
        uses: 'hashicorp/setup-terraform@v2'

      - name: 'Terraform Format'
        run: terraform fmt -check
        continue-on-error: true

      - name: 'Initialize Terraform Backend'
        run: terraform init
```

`terraform init` completes successfully in the push workflow. On the pull_request workflow, the `terraform init` step fails with:

```
Initializing the backend...
╷
│ Error: Failed to get existing workspaces: querying Cloud Storage failed: Get "https://storage.googleapis.com/storage/v1/b/<bucket name>/o?alt=json&delimiter=%2F&pageToken=&prefix=&prettyPrint=false&projection=full&versions=false": oauth2/google: status code 403: {
│   "error": {
│     "code": 403,
│     "message": "The caller does not have permission",
│     "status": "PERMISSION_DENIED"
│   }
│ }
```
Any ideas? Let me know if I can provide any extra information. Thanks in advance :smiley:.
