### ISSUE TITLE
Unable to read secrets from Azure KeyVault using OpenID Connect

### ISSUE THREAD

**Issue by alicyn** [hashicorp/setup-terraform#266]
I am following the guide here to configure authentication via OpenID connect, specifically for "GitHub actions deploying Azure resources" : https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_oidc
 
I am running Terraform in GitHub Actions to deploy an Azure Container Instance Group. Terraform (from GitHub Actions) needs to read secrets from an Azure Key Vault.
 
Terraform code: 

```
data "azurerm_key_vault_secret" "envvars" {
  name = "dotenvsecrets"
  key_vault_id = module.aci_kv.instance.id
}
```

Error in GitHub actions run: 
```
data.azurerm_key_vault_secret.envvars: Reading...

Error: making Read request on Azure KeyVault Secret dotenvsecrets: keyvault.BaseClient#GetSecret: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="Client address is not authorized and caller is not a trusted service.\r\nClient address: 13.83.40.213\r\nCaller: appid=***;oid=OBJECTID;iss=[https://sts.windows.net/***/\r\nVault:](https://sts.windows.net/***//r/nVault:) aci-kv;location=westus2" InnerError={"code":"ForbiddenByFirewall"}
```
GitHub Actions workflow: 
```
permissions:
  id-token: write 
  contents: read 

name: deploy

on:
  push

jobs:

  deploy-aci:
    name: deploy-aci
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.ref_name }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_USE_OIDC: true
      
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      
    - name: Setup terraform ENV variables
      run: echo "TF_VAR_branch_name=${{ env.BRANCH_NAME }}" >> $GITHUB_ENV

    - name: Setup terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
 ```
    
I have assigned both "Contributor" and "Azure Key Vault Secret User" RBAC roles to the Service Principal created for OIDC, but still encountering this error. 

I have RBAC authorization enabled for the KeyVault, and Network ACLs to block public access (the "firewall"). Interestingly, there appears to be only deprecated documentation available from Microsoft on fetching secrets from Key Vault using GitHub Actions: https://learn.microsoft.com/en-us/azure/developer/github/github-key-vault

Update: I have enabled "allow all networks/public access" for the Azure KeyVault and now the errors are gone, but ideally there should be a way to whitelist Terraform? (which I assumed was the whole point of using OIDC).

Has anyone encountered this?
