### ISSUE TITLE
How to leverage plan -out and apply

### ISSUE THREAD

**Issue by yordis** [hashicorp/setup-terraform#271]
Hey there, I am a bit confused about how I could set up the `terraform plan -out` and `terraform apply [file name]` 

It may be beneficial to showcase some examples demonstrating how it could be accomplished.

I thought it would be trivial, but I haven't been able to make it work with artifacts or however I suppose to make it work.

Here is what I got so far:

```yml
env:
  tf_working_dir: home/infrastructure/github/testing-project

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0

      - name: Get Terraform Version
        uses: straw-hat-team/github-actions-workflows/asdf/get-version@v1.5.1
        id: terraform-version
        with:
          plugin-name: terraform

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: ${{ steps.terraform-version.outputs.plugin-version }}
          terraform_wrapper: true

      - name: Terraform Format
        if: github.ref != 'refs/heads/master' && github.event_name == 'pull_request'
        run: terraform fmt -check
        working-directory: ${{ env.tf_working_dir }}

      - name: Terraform Init
        run: terraform init -backend=true
        working-directory: ${{ env.tf_working_dir }}

      - name: Terraform Validate
        if: github.ref != 'refs/heads/master' && github.event_name == 'pull_request'
        run: terraform validate
        working-directory: ${{ env.tf_working_dir }}

      - name: Terraform Plan
        if: github.ref != 'refs/heads/master' && github.event_name == 'pull_request'
        run: terraform plan -input=false -out=${{ github.sha }}.tfplan
        working-directory: ${{ env.tf_working_dir }}

      - name: Upload terraform Plan Artifact
        if: github.ref != 'refs/heads/master' && github.event_name == 'pull_request'
        uses: actions/upload-artifact@v3.1.1
        with:
          name: terraform-plan-${{ github.sha }}
          path: ${{ env.tf_working_dir }}/${{ github.sha }}.tfplan
          if-no-files-found: error

      - name: Download terraform Plan Artifact
        uses: actions/download-artifact@v3.0.1
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        with:
          name: terraform-plan-${{ github.sha }}
          path: ${{ env.tf_working_dir }}/${{ github.sha }}.tfplan

      - name: terraform Apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false ${{ github.sha }}.tfplan
        working-directory: ${{ env.tf_working_dir }}

```

I am not sure what is going with `github.sha` but it changes by the time it gets into `master` so the artifact is not found. Maybe you know what I am doing wrong or what I should be doing.

Thanks in advanced.
