### ISSUE TITLE
Setup terraform Erro: ##[error](s || "").replace is not a function

### ISSUE THREAD

**Issue by chengsh7** [hashicorp/setup-terraform#30]
Hi,
I hit the following error when running workflow in github. I am running it on self runner. Anyone can help?

```HashiCorp - Setup Terraform
 Run hashicorp/setup-terraform@v1.1.0
  with:
    cli_config_credentials_hostname: app.terraform.io
    terraform_version: latest
    terraform_wrapper: true
Latest version is 0.12.29
##[error](s || "").replace is not a function
```

My workflow file as below:

```
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v1.1.0

    - name: Terraform Init
      id: init
      run: terraform init
```
