### ISSUE TITLE
Get files from global folder

### ISSUE THREAD

**Issue by kaefferlein** [hashicorp/setup-terraform#309]
Hi all,

I have a question regarding the scopes of this action.

First of all let me show you the simplified repo structure:

```
project
└─── .github 
    │   some workflow files
└─── configuration
    │   containing some JSON files with customer details
└─── azure
    │   containing .tf files regarding azure resources
└─── gcp
    │   containing .tf files regarding GCP resources
```

Both folders contain terraform files for setting up resources in either Azure or GCP. 
Workspaces are located in Terraform Enterprise. Each folder (gcp and azure) reside in an own workspace.
Both folders rely on information stored in the `project/configuration/<someconfig>.json` folder.

Unfortunately I did not find a way to use the global configuration folder from the GitHub action part. Instead I had to copy the configuration folder to the azure and gcp folder, resulting in a repo structure like that:

```
project
└─── .github 
    │   some workflow files
└─── configuration
    │   containing some JSON files with customer details
└─── azure
    └─── configuration 
    │   containing .tf files regarding azure resources
└─── gcp
    └─── configuration 
    │   containing .tf files regarding GCP resources
```

As I want to avoid duplicate code (even if it's just copied/pasted via another GH action) I wanted to know if it's possible to stick to the first example repo structure and get the contents of the configuration files from the global folder.

Following you can see an excerpt from the GH action:

```
name: "Terraform"

env:
  work-dir: gcp
  cli_config_credentials_hostname: my-host.com

on:
  push:
    branches:
      - gha # todo change to dev
  pull_request:

jobs:
  github:
    name: "Terraform run for GCP"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7
          cli_config_credentials_token: ${{ secrets.TOKEN }}
          cli_config_credentials_hostname: ${{ env.cli_config_credentials_hostname }}

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ${{ env.work-dir }}

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: ${{ env.work-dir }}

      - name: Terraform Plan
        id: plan
        run: terraform  plan -input=false
        working-directory: ${{ env.work-dir }}
        continue-on-error: true
```

Within Terraform I get the files like that (note: when getting the files from the copied configuration sub folders):
```hcl
fileList = fileset(path.module, "customers/**/*.json")
```

Any help would be highly appreciated. :)

Best,
Anna
