### ISSUE TITLE
##[error](s || "").replace is not a function

### ISSUE THREAD

**Issue by hazcod** [hashicorp/setup-terraform#36]
Hi, trying the new action for setting up terraform.
Yaml:
```yaml
  -
      name: Extract terraform version
      run: |
        echo ::set-env name=terraform_version::"$(./.github/extract-version.sh .github/terraform/go.mod | jq -r .version | cut -d v -f 1)"
        echo "terraform version is ${{ env.terraform_version }}"
    - 
      name: Setup terraform ${{ env.terraform_version }}
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.terraform_version }}
```

But this results in:
```
Run hashicorp/setup-terraform@v1
  with:
    terraform_version: 1.13.0
    cli_config_credentials_hostname: app.terraform.io
    terraform_wrapper: true
  env:
    terraform_version: 1.13.0
    k8s_version: 1.18.3
##[error](s || "").replace is not a function
```

Any ideas?
