### ISSUE TITLE
If an API Token is supplied as a secret to the script it is not recognized further in CI

### ISSUE THREAD

**Issue by DanilKrymskyi** [hashicorp/setup-terraform#368]
Hello there!

Encountering an issue when providing the API Token via `cli_config_credentials_token` as a secret results in the following error:
```yaml
- name: Set up Terraform
  uses: hashicorp/setup-terraform@v2
  with:
    terraform_version: 1.6.2
    cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    
- name: Initialize Terraform
  run: terraform init
```

```plaintext
Error: Required token could not be found

Run the following command to generate a token for app.terraform.io:
terraform login
```

Error: Terraform exited with code 1.
Error: Process completed with exit code 1.

However, if the token is passed as a variable using `vars.`, it works correctly and results in **Terraform Cloud being successfully initialized!**

```yaml
- name: Set up Terraform
  uses: hashicorp/setup-terraform@v2
  with:
    terraform_version: 1.6.2
    cli_config_credentials_token: ${{ vars.TF_API_TOKEN }}
    
- name: Initialize Terraform
  run: terraform init
```
