### ISSUE TITLE
With upgrade to v3, terrafrom init in github actions fails with wrapper enabled 

### ISSUE THREAD

**Issue by pribanerjee** [hashicorp/setup-terraform#373]
We just upgraded to hashicorp/setup-terraform@v3 for our GitHub actions and it started failing in **terraform init step** with below error 
```
/actions-runner/_temp/e6023f8c-517d-4123-8609-5827ed8f73a7/terraform:4342
      this._parser?.end()
                   ^


SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:10[27](https://github.com/OttoPaymentHub/bigfin_api-gateway/actions/runs/6704783026/job/18217882380#step:9:28):10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
Error: Process completed with exit code 1.
```

Terraform Configuration Files:

```
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.6.0'
          terraform_wrapper: true
```
      
  It only works when we disable the    **terraform_wrapper**, which is not expected as we would like to work with exit codes.

Please look into the issue.
