### ISSUE TITLE
Fails with AggregateError in self-hosted runners

### ISSUE THREAD

**Issue by yashid-mohamed** [hashicorp/setup-terraform#425]
Hi,

We are facing this issue where the **setup-terraform@v3** action starts to fail with an **AggregateError** when this action is being invoked within a GitHub Actions self hosted runner (ubuntu 22.04) hosted in a Azure Kubernetes cluster using Actions Runner Controller.

**Failed Run**

`##[debug]Evaluating condition for step: 'Run hashicorp/setup-terraform@v3'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Run hashicorp/setup-terraform@v[3](https://github.com/yashid-mohamed/my-test-app/actions/runs/9842799277/job/27172577799#step:4:3)
##[debug]Loading inputs
##[debug]Loading env
Run hashicorp/setup-terraform@v3
##[debug]Finding releases for Terraform version ~1.0
**Error: AggregateError**
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Run hashicorp/setup-terraform@v3`

I suspect that we might hitting a rate limit issue because the same action (workflow) works fine when executed later after a period of time or the next day.

**Successful Run**

`##[debug]Evaluating condition for step: 'Run hashicorp/setup-terraform@v3'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Run hashicorp/setup-terraform@v3
##[debug]Loading inputs
##[debug]Loading env
Run hashicorp/setup-terraform@v3
##[debug]Finding releases for Terraform version ~1.0
##[debug]Getting build for Terraform version 1.0.11: linux amd64
##[debug]Downloading Terraform CLI from https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip
##[debug]Downloading https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip
##[debug]Destination /home/runner/_work/_temp/43b4ccd6-66ca-4abd-b118-9e973a0d0cb[2](https://github.com/yashid-mohamed/my-test-app/actions/runs/9855362015/job/27240248601#step:4:2)
##[debug]download complete
##[debug]Extracting Terraform CLI zip file
/usr/bin/unzip -o /home/runner/_work/_temp/4[3](https://github.com/yashid-mohamed/my-test-app/actions/runs/9855362015/job/27240248601#step:4:3)b4ccd6-66ca-4abd-b118-9e973a0d0cb2
Archive:  /home/runner/_work/_temp/[4](https://github.com/yashid-mohamed/my-test-app/actions/runs/9855362015/job/27240248601#step:4:4)3b4ccd6-66ca-4abd-b118-9e973a0d0cb2
  inflating: terraform               
##[debug]Terraform CLI path is /home/runner/_work/_temp/e228[5](https://github.com/yashid-mohamed/my-test-app/actions/runs/9855362015/job/27240248601#step:4:5)ab8-10f1-4d98-b69d-9dc424a5c348.
##[debug]Node Action run completed with exit code 0
##[debug]Finishing: Run hashicorp/setup-terraform@v3`

Can someone please help shed some light on why the action fails with an AggregateError and also how we can overcome this while using self-hosted GitHub runners?

Thanks!

Note - that I'm installing node v20.15.0 in a previous step in the same workflow using the **setup-node@v4** action. We have not seen this issue occur when using the GitHub hosted runners.

**Comment by V-know** [comment]
Add one more scenario.
We are facing the same issue now.
```
Run hashicorp/setup-terraform@v3
  with:
    cli_config_credentials_hostname: app.terraform.io
    terraform_version: latest
    terraform_wrapper: true
  env:
    ALICLOUD_ACCESS_KEY_SECRET: ***
    ALIBABA_CLOUD_SECURITY_TOKEN: ***
    ALICLOUD_ACCESS_KEY_STS_TOKEN: ***
    ALIBABACLOUD_SECURITY_TOKEN: ***
    ALICLOUD_SECURITY_TOKEN: ***
Error: AggregateError
```

We use `apt-get` to install terraform as the workaround solution, it works.
But we still want to know the root cause and hope to fix this problem as soon as possible. Thank you.

```
     - name: 'Terraform Setup'
        run: |
          sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
          wget -O- https://apt.releases.hashicorp.com/gpg | \
          gpg --dearmor | \
          sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
          gpg --no-default-keyring \
          --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg \
          --fingerprint
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
          https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
          sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update
          sudo apt-get install terraform
```

**Comment by raveheart1** [comment]
Seeing the same error on setup-terraform@v1 on self-hosted runners. Ubuntu 20.04 for us.

## Issue Summary

### Deprecation Warning and AggregateError

When running the `hashicorp/setup-terraform@v1` GitHub Action, a deprecation warning and an `AggregateError` are encountered. Below is the relevant section of the GitHub Action workflow:

```yaml
Run hashicorp/setup-terraform@v1
  with:
    terraform_wrapper: false
    cli_config_credentials_hostname: app.terraform.io
    terraform_version: latest
  env:
    tf_actions_working_dir: ***
    ARM_ENVIRONMENT: usgovernment
    TF_VAR_USERNAME: ***
    TF_VAR_PASSWORD: ***
    TF_VAR_VPNGW_SHARED_KEY: ***
    TF_VAR_WINDOWS_ADMIN: ***
    TF_VAR_WINDOWS_PASSWORD: ***
    ARM_SKIP_PROVIDER_REGISTRATION: true
(node:10156) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Error: AggregateError
```

## Steps to Reproduce

1. Set up a GitHub Actions workflow with the `hashicorp/setup-terraform@v1` action.
2. Configure the action with the following parameters:
    ```yaml
    with:
      terraform_wrapper: false
      cli_config_credentials_hostname: app.terraform.io
      terraform_version: latest
    env:
      tf_actions_working_dir: ***
      ARM_ENVIRONMENT: usgovernment
      TF_VAR_USERNAME: ***
      TF_VAR_PASSWORD: ***
      TF_VAR_VPNGW_SHARED_KEY: ***
      TF_VAR_WINDOWS_ADMIN: ***
      TF_VAR_WINDOWS_PASSWORD: ***
      ARM_SKIP_PROVIDER_REGISTRATION: true
    ```
3. Run the GitHub Action.

## Expected Behavior

The GitHub Action should set up Terraform without any warnings or errors.

## Actual Behavior

- A deprecation warning is displayed:
  ```
  (node:10156) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
  (Use `node --trace-deprecation ...` to show where the warning was created)
  ```
- An `AggregateError` is thrown, causing the action to fail.

## Environment

- GitHub Actions Runner
- `hashicorp/setup-terraform@v1`
- Terraform version: `latest`

## Additional Context

The deprecation warning indicates that the `Buffer()` constructor is being used, which is deprecated in favor of `Buffer.alloc()`, `Buffer.allocUnsafe()`, or `Buffer.from()` due to security and usability issues. This warning suggests that the action or its dependencies may need an update to address this deprecated usage.

The `AggregateError` is less clear without additional stack trace information. It may indicate multiple errors occurring simultaneously. Running the action with `node --trace-deprecation` could provide more insight into the source of the warning and error.


## Contact

Please reach out if you need more information or have questions regarding this issue.

---

Thank you for your attention to this matter. We look forward to your response and resolution.
