### ISSUE TITLE
Terraform init uses version 1.9.5 instead of installed version 1.10.1 

### ISSUE THREAD

**Issue by chriscloud27** [hashicorp/setup-terraform#451]
I am updating the terraform version to 1.10.1 and tf version confirms that. In the tf init the version 1.9.5 is used which I do not understand. I am using the Tf Cloud with my workspace setting on ~>1.10.0. Still, I do not understand why the Github runner versions differs. Can someone help me?

```
name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Remove any pre-installed Terraform version (if necessary)
    - name: Remove Pre-Installed Terraform (if any)
      run: sudo rm -rf $(which terraform)

    # Install the correct Terraform version and configure Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
        terraform_version_file: '.terraformrc'
        terraform_version: "1.10.1"

    # Check the Terraform version to verify the correct version is installed
    - name: Check Terraform Version
      run: terraform version

    # Initialize Terraform working directory
    - name: Terraform Init
      run: terraform init -upgrade

    # Check formatting of Terraform files
    - name: Terraform Format
      run: terraform fmt -recursive

    # Generate an execution plan
    - name: Terraform Plan
      run: terraform plan -input=false

    # Apply the configuration on push to the "main" branch
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false
```

Output of the action:
<img width="657" alt="image" src="https://github.com/user-attachments/assets/4ce4b04f-4c88-40b9-980d-d5e7bbcbe29b">
