### ISSUE TITLE
Segmentation fault  `terraform version -json` for an ARM runner

### ISSUE THREAD

**Issue by extsoft** [hashicorp/setup-terraform#459]
`terraform version -json` generates the `2458 Segmentation fault` error for the ARM runners.

The GitHub Actions workflow uses a GitHub-managed custom runner with the following configuration:

1. Size: 4-cores · 16 GB RAM · 150 GB SSD (2-cores have this issue as well)
2. Public IP: Disabled
3. Network Configuration: Disabled
4. Image source: Partner
5. Image name: Ubuntu 24.04 by Arm Limited

The "Some logic" step from the workflow below

```yaml
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Some logic
        run: |
          tf_version=$(terraform version -json | jq -r ".terraform_version")
```

fails with the `Error: Process completed with exit code 139.` error.

After doing a magic trick by ignoring the first failure of the `terraform version -json` command, the workflow is executed successfully. The fix looks like

```yaml
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Some logic
        run: |
          set -x
          # Workaround
          (terraform version -json && echo "The first 'terraform version -json' succeeded.") || {
            echo "The first 'terraform version -json' failed. Retrying..."
            terraform version -json
            echo "The second 'terraform version -json' succeeded."
          }
          # Logic
          tf_version=$(terraform version -json | jq -r ".terraform_version")
```

It generates output like

```txt
Run set -x
+ terraform version -json
/home/runner/work/_temp/3c8f6d48-1ca4-4ac4-aed7-fd587ca1a3a1.sh: line 3:  2458 Segmentation fault      (core dumped) terraform version -json
+ echo 'The first '\''terraform version -json'\'' failed. Retrying...'
The first 'terraform version -json' failed. Retrying...
+ terraform version -json
{
  "terraform_version": "1.8.5",
  "platform": "linux_arm64",
  "provider_selections": {
    "registry.terraform.io/hashicorp/aws": "5.58.0"
  },
  "terraform_outdated": true
}
+ echo 'The second '\''terraform version -json'\'' succeeded.'
The second 'terraform version -json' succeeded.
```

While I have such a magic workaround, I still do not understand the source of the failure. Please help to solve this problem permanently.
