### ISSUE TITLE
setup-terraform throws [error](s || "").replace is not a function

### ISSUE THREAD

**Issue by statwoodland** [hashicorp/setup-terraform#5]
I tried switching to this action given that it it recently succeed [terraform-github-actions](https://github.com/hashicorp/terraform-github-actions). Unfortunately, I get this error:

```
  Run hashicorp/setup-terraform@v11s
##[error](s || "").replace is not a function
Run hashicorp/setup-terraform@v1
  with:
    terraform_version: 0.11.13
    cli_config_credentials_hostname: app.terraform.io
    terraform_wrapper: true
##[error](s || "").replace is not a function
```

Relevant config:

```
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.11.13
```

I am not supplying credentials because I don't use Cloud/Enterprise, my backend is in S3. Terraform is given permission to access it via a self-hosted IAM runner, which worked fine with terraform-github-actions.

Am I correct in assuming that it is expecting a password? Just to clarify, this action doesn't _only_ work for Cloud/Enterprise, does it? Supporting only one backend would be a dramatic reduction in utility from the now-unsupported version...

**Comment by sudomateo** [comment]
> Just to clarify, this action doesn't only work for Cloud/Enterprise, does it?

It supports any backend Terraform CLI supports.

I just tested using the `s3` backend with the following GitHub Actions workflow.

```
name: 'Terraform'

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.11.13

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: terraform apply -auto-approve
```

In my test I'm using AWS API tokens to authenticate, but Terraform was able to successfully initialize the `s3` backend and store state in there.

Here's the relevant `main.tf` I used.

```
terraform {
  backend "s3" {
    bucket = "redacted"
    key    = "redacted"
    region = "us-east-1"
  }
}

resource "null_resource" "terraform-github-actions" {
  triggers = {
    value = "This resource was created using GitHub Actions!"
  }
}
```

A screenshot showing my run.

![actions-s3](https://user-images.githubusercontent.com/24284972/81369770-4fcacc80-90c1-11ea-820c-5dc9b3b614e6.png)

**Comment by solomson** [comment]
Working example for Azure with service principal if anyone comes looking, was struggling a bit.
Get the secrets from  
` az ad sp create-for-rbac --name terraform --role "Owner" --scopes/subscriptions/yoursubscriptionid --sdk-auth ` (note that this SP is as powerful as any subscription admin)

main.tf

```

terraform {
  backend "azurerm" {
    resource_group_name  = "xxx"
    storage_account_name = "yyy"
    container_name       = "tfstate-prod"
    key                  = "tfstate"
  }
}

provider "azurerm" {
  version = "~>2.0"
  features {}
} 


```
ci.yml

```
name: 'Terraform Plan'
on: [push, pull_request]
defaults:
      run:
        shell: bash

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Terraform Setup'
        uses: hashicorp/setup-terraform@v1

      - name: 'Terraform Init'
        run: terraform init

      - name: 'Terraform Plan'
        id: plan
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terraform apply -auto-approve
```

**Comment by statwoodland** [comment]
Thanks for the very clear start-to-finish example, @sudomateo, it is much appreciated! 👍 

Unfortunately I still have this error despite our setup configuration being identical.

```
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.11.13
```

Our only difference is that this is a self-hosted runner on an EC2 instance with an IAM role. I know the credentials are present and obtainable as `hashicorp/terraform-github-actions` is running successfully on the same host. No special configuration was necessary. As an example:

```
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: '0.11.13'
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: 'terraform/'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I'll continue to look in to the source of this error message...

**Comment by sudomateo** [comment]
You're welcome @statwoodland!. Since this is a self-hosted runner, it's possible there is a software version difference on your self-hosted runner preventing the `hashicorp/setup-terraform` action from executing.

I would recommend [enabling debug logging](https://help.github.com/en/actions/configuring-and-managing-workflows/managing-a-workflow-run#enabling-debug-logging) to gather more information.

**Comment by AnthonyHerman** [comment]
I'm getting the same thing using a self-hosted runner with remote state on app.terraform.io ->

```
##[debug]Evaluating condition for step: 'Setup Terraform'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Setup Terraform
##[debug]Loading inputs
##[debug]Evaluating: secrets.TF_API_TOKEN
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'TF_API_TOKEN'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Loading env
Run hashicorp/setup-terraform@v1
  with:
    terraform_version: latest
    cli_config_credentials_hostname: app.terraform.io
    cli_config_credentials_token: ***
    terraform_wrapper: true
  env:
    GITHUB_TOKEN: ***
    TF_VAR_vault_token: ***
##[debug]Downloading version metadata
##[debug]Parsing version list for latest version
##[debug]Getting build for Terraform version 0.12.24, os linux, and arch x64
##[debug]Downloading Terraform CLI from https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
##[debug]Downloading https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
##[debug]Destination /home/security/actions-runner/_work/_temp/acfea5e5-c29f-4fa0-83e3-07a4c7592854
##[debug]download complete
##[debug]Extracting Terraform CLI zip file
##[error](s || "").replace is not a function
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Setup Terraform
```

**Comment by sudomateo** [comment]
I was able to reproduce this with a vanilla Ubuntu 18.04.4 LTS self-hosted runner. The upstream `@actions/tool-cache` library uses `unzip` to unzip the downloaded Terraform ZIP file. My self-hosted runner did not have `unzip` installed. Installing `unzip` on the self-hosted runner resolved this issue.

The SaaS GitHub Actions Ubuntu 18.04 runner comes with `unzip` installed by default as [detailed here](https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md) which is why it works in SaaS.

**Comment by AnthonyHerman** [comment]
Cool that worked to get past setup. Aside from unzip I had to install nodejs12 -> 

https://github.com/nodesource/distributions/blob/master/README.md
```
Node.js v12.x:    
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt-get install -y nodejs
```

Since apt install was giving me 8 and that was causing it to fail at another step.

**Comment by sudomateo** [comment]
Glad to hear it!

Node.js 12 is a hard requirement for this action (and most JavaScript actions if I'm not mistaken) as that is what is was tested against. The [Creating a JavaScript action](https://help.github.com/en/actions/building-actions/creating-a-javascript-action) documentation assumes Node.js 12.

I'll wait for the original poster of this issue to comment back before closing.

**Comment by statwoodland** [comment]
Installing `unzip` did the trick. So the root cause was ignorance on my part for not realizing that self-hosted runners require a lot more set-up than [the docs imply](https://help.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners). 

Because the fix was unrelated to the setup-terraform action itself, you deserve an extra big "thank you", @sudomateo ! 🙌

**Comment by shiplu** [comment]
Those who are here to find a solution, I am sharing my solution here so you can also try it.

I used `v0.12.28` as the version as it was the output of `terraform -version`. But note this has a **v** in front of the version name. My last log line was before showing `[error](s || "").replace is not a function`

    Parsing version list for version v0.12.28

Then I realized and removed the `v` and it worked afterward. So if the version you are specifying is non-existing or  `hashicorp/setup-terraform@v1` returns an empty list when it searches using the version specified, you'll face this error. 

*Check your version literally.*

**Comment by davegallant** [comment]
Ran into this while participating in the v0.13.0 beta program.

Can confirm the following does work:

```yaml
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "0.13.0-rc1"
```
