### ISSUE TITLE
How do you export a generated ARN back to a github pipeline?

### ISSUE THREAD

**Issue by Shadrack1701** [hashicorp/setup-terraform#67]
I'm working on a project using this library to set up my aws environment for a serverless-nextjs project.  I would really love to be able to export some (or all) of the generated arns from the setup-terraform action to pass into my serverless command.  This would automate my process much more and make it dynamic.  Is this possible with this action? 

If this is not possible with setup-terraform, does anyone know how I can through another github action/script to dynamically retrieve arns from my aws account?

If no-one wants to answer the second part I understand as it's unrelated to this repo so I can make a StackOverflow question for it.  Just checking if any local experts know.

Thanks!
Matt Trachsel

**Comment by alexjurkiewicz** [comment]
The setup-terraform action installs Terraform. Running Terraform is up to you. It sounds like you want a process like this:

```yaml
- uses: hashicorp/setup-terraform@master
- run: terraform apply
- run: |
    echo "My output value is:"
    terraform output myoutput
```

This uses a Terraform [output](https://www.terraform.io/docs/configuration/outputs.html).
