### ISSUE TITLE
Terraform Plan Pull Request Comment Incorrectly Formatted

### ISSUE THREAD

**Issue by stevenpall** [hashicorp/setup-terraform#74]
Hi there,

I'm not sure if this is an issue with this action, however I wanted to point out that the example given in the docs of commenting on a PR from the output of the `terraform plan` step does not produce an output formatted correctly. More specifically, it appears the triple backticks are not working correctly to place the output in a code block (as seen below).
![Screen Shot 2020-12-07 at 11 51 31 AM](https://user-images.githubusercontent.com/2805687/101402497-ae8b3b00-3888-11eb-8552-9a361afc38c4.png)

This may be an issue with the `github-script` action this step uses, however I can't figure out the origin of the issue. For reference, here is my workflow file:
```
name: Dev

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  TF_WORKSPACE: dev

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_version: 0.13.2

      - name: Terraform format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color
        continue-on-error: true

      - name: Update Pull Request
        uses: actions/github-script@v3.1.0
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
            <details><summary>Show Plan</summary>
            ```${process.env.PLAN}```
            </details>
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
              
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terraform apply -auto-approve
```
This is all pretty stock as far as I can tell. Any help here would be appreciated. Thanks!
