### ISSUE TITLE
can use multi version?

### ISSUE THREAD

**Issue by yuzujoe** [hashicorp/setup-terraform#82]
Hi,

Is it possible to have multiple terraform versions coexist using setup-terraform?

I'm planning to migrate from 0.13 to 0.14 and would like to run each plan separately as it would take a lot of time to plan for all directories.

**Comment by ksatirli** [comment]
Hey @yuzujoe I think I can help with this:

`setup-terraform` takes its version configuration from `terraform_version`:

```yml
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "0.14.7"
```

One way to build this is to use different job descriptions inside your GHA Workflow files to define the versions:

```yml
jobs:
  zerothirteen:
    name: terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "0.13.2"

      - name: Run `terraform init` on `project-1`
        run: terraform init -backend=false -get=true -get-plugins=true "./project-0/"

  zerofourteen:
    name: terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "0.14.7"

      - name: Run `terraform init` on `project-1`
        run: terraform init -backend=false -get=true -get-plugins=true "./project-1/"
``` 

This would give you access to `0.13.2`. for your IaC in `./project-0/` and `0.14.7` for your IaC in `./project-1/`.

Does this help?

**Comment by evanfreed** [comment]
@ksatirli the suggestion above would work but any future upgrades would need similar intervention and becomes tedious or overly manual to manage at scale.

I think the ideal feature would be if `setup-terraform` was capable of detecting the workspace version based on the value provided in the workspaces required_version field.

```hcl
terraform {
  required_version = ">= 0.14" # would set terraform_version to latest version of 0.14.x
}
```

I believe this would be the preferred route but another alternative is to take the route of tfenv (for example) and read the version from each workspace from a file (.terraform-version).  Thoughts?

**Comment by yuzujoe** [comment]
I dealt with it by treating the information in .terraform-version as an environment variable.

```yaml
        run: |
          printf "TF_VERSION=%s" $(cat .terraform-version) >> $GITHUB_ENV

- name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}
```
