### ISSUE TITLE
Plan taking too much to run

### ISSUE THREAD

**Issue by renanz** [hashicorp/setup-terraform#92]
When using the terraform github action, the plan step takes too much time.

I'm using the following configuration. I've also tried using github action v1
```yaml
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_version: 0.12.28
      - name: Terraform Init
        working-directory: ci/terraform
        env:
          KEY: ${{ steps.extract_vars.outputs.key }}
        run: terraform init -upgrade -input=false -backend-config="key=$KEY" -backend-config="bucket=$TERRAFORM_S3_BUCKET"
      - name: Terraform Plan
        working-directory: ci/terraform
        run: terraform plan
```

![image](https://user-images.githubusercontent.com/16767745/106364505-227c1980-62f5-11eb-9389-edb51b83c095.png)

![image](https://user-images.githubusercontent.com/16767745/106364510-3293f900-62f5-11eb-9c98-ae911bba926b.png)
