### ISSUE TITLE
Terraform CLI commands run in parallel in github actions and cloud

### ISSUE THREAD

**Issue by artvichi** [hashicorp/setup-terraform#95]
Hi! There is a problem for our team with multiple build launched from github actions.

Current Behavior: 

When I use example provided in the docs I see that there are two builds running:
- one in github actions 
- one in terraform cloud

Looks like this is wrong, also they conflict and fail both because of that (ending up with errors that same resource was already created)

Desired behavior: 

Run only one build in github actions or terraform cloud. And save terraform state to be able remove infrastracture later.

release.yml workflow which runs on merge to `release` brunch

```
 env:
      working-directory: ./tf
```
...
```
- name: Setup Terraform
  uses: hashicorp/setup-terraform@v1
  with:
    # terraform_version: 0.13.0:
    cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

- name: Terraform Format
  run: terraform fmt -check
  working-directory: ${{ env.working-directory }}

- name: Terraform Init
  run: terraform init
  env:
    GOOGLE_CREDENTIALS: ${{ secrets.TF_SA_KEY }}
  working-directory: ${{ env.working-directory }} 

- name: Terraform Plan
  run: terraform plan -no-color
  env:
    GOOGLE_CREDENTIALS: ${{ secrets.TF_SA_KEY }}
  working-directory: ${{env.working-directory}} 

- name: Terraform Apply
  run: terraform apply -auto-approve
  env:
    GOOGLE_CREDENTIALS: ${{ secrets.TF_SA_KEY }}
  working-directory: ${{env.working-directory}}
```

tf/main.tf

```
terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "3.58.0"
    }
  }
}

provider "google" {
  project = var.project
  region  = var.region
  zone    = var.zone
}

resource "google_project_service" "run" {
  service = "run.googleapis.com"
}

resource "google_cloud_run_service" "service" {
  depends_on = [google_project_service.run]
  name       = var.service
  location   = var.region

  template {
    spec {
      containers {
        image = "us.gcr.io/dummy/${var.service}:${var.container}"
        ports {
          container_port = 7022
        }
      }
    }
  }

  traffic {
    percent         = 100
    latest_revision = true
  }
}

resource "google_cloud_run_service_iam_member" "allUsers" {
  service  = google_cloud_run_service.service.name
  location = google_cloud_run_service.service.location
  role     = "roles/run.invoker"
  member   = "allUsers"
}

resource "google_cloud_run_domain_mapping" "service_domain_mapping" {
  location = var.region
  name     = "${var.service}.dummy.com"

  metadata {
    namespace = var.project
  }

  spec {
    route_name = google_cloud_run_service.service.name
  }
}


resource "google_api_gateway_api" "service-api" {
  provider = google-beta
  api_id   = "${var.service}-api"
  project  = var.project
}

resource "google_api_gateway_api_config" "service-api-config" {
  provider      = google-beta
  api           = google_api_gateway_api.service-api.api_id
  api_config_id = "${var.service}-api-config"
  project       = var.project

  openapi_documents {
    document {
      path     = "spec.yaml"
      contents = filebase64("spec.yaml")
    }
  }
}

resource "google_api_gateway_gateway" "service-api-gateway" {
  provider   = google-beta
  project    = var.project
  region     = var.region
  api_config = google_api_gateway_api_config.service-api-config.id
  gateway_id = "${var.service}-api-gateway"
}

```

tf/variables.tf

```
variable "service" {
  type    = string
  default = "some-service"
}

variable "project" {
  type    = string
  default = "dummy"
}

variable "region" {
  type    = string
  default = "us-central1"
}

variable "zone" {
  type    = string
  default = "us-central1-c"
}

variable "container" {
  type    = string
  default = "dummy"
}

```

Thanks! Please let me know if you need additional information
