### ISSUE TITLE
Support for multiple directories

### ISSUE THREAD

**Issue by AydarAkhmetzyanov** [hashicorp/setup-terraform#99]
Is it a way to implement github_actions workflow with multiple folders for projects/environments?  Now it ignores any subfolder...

**Comment by ljakimczuk** [comment]
Hi @AydarAkhmetzyanov, I've just noticed your question looking for some other issue myself, I believe you could easily do it by, for example, looping through all directories with the `*.tf` files and then using `terraform -chdir=$dir plan` on each.

**Comment by lundbird** [comment]
Heads up for others encountering the same issue. I solved this using github actions matrices where each matrix value is the directory to do a terraform build.

I used this tool https://github.com/dorny/paths-filter to determine the paths changed in an initial job to fill out the matrix values.

**Comment by tobiasbueschel** [comment]
@AydarAkhmetzyanov here's an example for the matrix strategy that @lundbird mentioned - hope it helps you :) 

```yml
  build-and-test:
    name: CI Pipeline
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix: { env: ["development", "production"] }
    environment: ${{ matrix.env }}
    defaults:
      run:
        working-directory: "./workspaces/${{ matrix.env }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Verify that the configuration files are syntactically valid
        run: terraform validate -no-color

      - name: Terraform Plan
        run: terraform plan -no-color
```
